services:
  dotnetWebApi:
    image: dotnetwebapi
    build:
      context: .
      dockerfile: dotnetWebApi/Dockerfile

  dotnetwebapi:
    image: dotnetwebapi
    build:
      context: .
      dockerfile: dotnetWebApi/Dockerfile
