services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    
  dotnetWebApi:
    image: dotnetwebapi
    build:
      context: .
      dockerfile: dotnetWebApi/Dockerfile
    container_name: webApi
    restart: always
    depends_on:
      - db
      - minio
    environment:
      CONNECTION_STRING: "Host=db;Port=5432;Database=${DB_NAME};Username=${DB_USERNAME};Password=${DB_PASSWORD}"
      ISSUER: "https://localhost"
      AUDIENCE: "local-client"
      SECRETKEY: ${SECRET_KEY}
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      DOTNET_USE_POLLING_FILE_WATCHER: "1"
    ports:  
      - "5100:5100"
      - "5101:5101"
      - "9229:9229"
    volumes:
      - data_protection_keys:/app/keys
      - ./dotnetWebApi:/app # Монтируем код для live-отладки
    command: [ "dotnet", "watch", "run", "--no-launch-profile", "--no-hot-reload", "--urls", "http://0.0.0.0:5100" ]
    
  frontend:
    image: frontend-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    depends_on:
      - dotnetWebApi 
    ports:
      - "3000:80" 
    environment:
      - NODE_ENV=production 
    volumes:
      - ./frontend:/app
  
volumes:
  db_data:
  minio_data:
  data_protection_keys: